### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by repi** [Technolution/rustig#1]
The README says to use `cargo install --git https://github.com/Technolution/rustig` but doing this outputs:

> error: multiple packages with binaries found: arithmetic, binary_search, capturing_closure_invocation, direct, empty, hello_world, indexing, indirect, lib_calls, multi_dep, rustig, threads, trait_invocation, unwrap

Tried specifying the rustic binary with `cargo install --git https://github.com/Technolution/rustig --bin rustig` but that resulted in the same error

**Comment by Michael-F-Bryan** [comment]
Drop the `--bin`. There are multiple rust projects in this repo so you install it as `cargo install --git <repo> <binary>`.

```
cargo install --git https://github.com/Technolution/rustig rustig
```

**Comment by egrtechno** [comment]
Good point, I'll fix it in the README.md

**Comment by repi** [comment]
Thanks!
